# Usar la imagen oficial de Node.js como base
FROM node:20

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Compilar la aplicación
RUN npm run build

# Exponer el puerto en el que la aplicación va a correr
EXPOSE 3000

# Comando para correr la aplicación
CMD ["npm", "run", "start"]
